apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akuity-t4
  namespace: akuity
spec:
  project: default

  source:
    repoURL: https://github.com/TechHub01/WeatherForecast.git
    targetRevision: HEAD
    path: test4
  destination: 
    server: http://cluster-test-argo:8001
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
