apiVersion: v1
kind: Service
metadata:
  name: weatherapiser-t6
  namespace: cc-dev
spec:
  selector:
    app: weatherapidep-t6
  ports:
    - name: http
      port: 8099
      targetPort: 80
  type: LoadBalancer