apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi
  namespace: cc-dep
  labels:
    app: weatherapidep
spec:
  selector:
    matchLabels:
      app: weatherapidep
  template:
    metadata:
      labels:
        app: weatherapidep
    spec:
      containers:
      - name: weatherapidep
        image: mytestacr46.azurecr.io/argo-test/weather:v22
        ports:
        - containerPort: 80