apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-t4
  namespace: cc-dev
  labels:
    app: weatherapidep-t4
spec:
  selector:
    matchLabels:
      app: weatherapidep-t4
  template:
    metadata:
      labels:
        app: weatherapidep-t4
    spec:
      containers:
      - name: weatherapidep-t4
        image: mytestacr46.azurecr.io/argo-test/weather:v25
        ports:
        - containerPort: 80