apiVersion: v1
kind: Service
metadata:
  name: weatherapiser-t4
  namespace: cc-dev
spec:
  selector:
    app: weatherapidep-t4
  ports:
    - name: http
      port: 8098
      targetPort: 80
  type: LoadBalancer